export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_FAIL = 'HOME_FAIL';

export const COOPERATION_REQUEST = 'COOPERATION_REQUEST';
export const COOPERATION_SUCCESS = 'COOPERATION_SUCCESS';
export const COOPERATION_FAIL = 'COOPERATION_FAIL';

export const ABOUT_REQUEST = 'ABOUT_REQUEST';
export const ABOUT_SUCCESS = 'ABOUT_SUCCESS';
export const ABOUT_FAIL = 'ABOUT_FAIL';

export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const NEWS_FAIL = 'NEWS_FAIL';

export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';

export const PROGRAM_DETAILS_REQUEST = 'PROGRAM_DETAILS_REQUEST';
export const PROGRAM_DETAILS_SUCCESS = 'PROGRAM_DETAILS_SUCCESS';
export const PROGRAM_DETAILS_FAIL = 'PROGRAM_DETAILS_FAIL';